### ISSUE TITLE
Does not work with kubelogin

### ISSUE THREAD

**Issue by jordanrinke** [flavio/kuberlr#37]
Attempting to use kuberlr with a cluster that is configured for OIDC login with kubelogin produces non stop errors `W0705 17:53:09.023969   65547 transport.go:243] Unable to cancel request for *exec.roundTripper`

**Comment by jordanrinke** [comment]
Similar mentions here [https://github.com/rancher-sandbox/rancher-desktop/issues/1308](https://github.com/rancher-sandbox/rancher-desktop/issues/1308) and here [https://github.com/int128/kubelogin/issues/831]( https://github.com/int128/kubelogin/issues/831)

**Comment by hanlaur** [comment]
In my case, I observed thousands of `kubectl oidc-login` processes, freezing the terminal.

If I interpret what I am seeing right, kuberlr causes "infinite recursion" when oidc-login is used.  kuberlr tries to determine target cluster version first to decide on right kubectl version. To do that, it authenticates with k8s API. The authentication obeys settings from `$HOME/.kube/config`. In case of oidc-login, authentication causes invocation of `kubectl oidc-login`, and the recursion is ready.

Example of $HOME/.kube/config:
```
users:
- name: oidcuser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://xxxx
      - --oidc-client-id=xxx
      - --oidc-extra-scope=email
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
It seems possible to workaround the issue by modifying the config to invoke `kubectl-oidc_login` directly, instead of `kubectl oidc-login`, OR by changing the `command:` to have explicit path for kubectl.

But it would be great if `kuberlr` was enhanced to detect and avoid the recursion.
